---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-ubuntu:20.04}
    # env:
    #   http_proxy: ${http_proxy}
    #   https_proxy: ${https_proxy}
    #   no_proxy: ${no_proxy}
    groups:
      - adduser
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 2
scenario:
  name: default
verifier:
  name: ansible
