---

- name: Verify
  hosts: adduser
  tasks:
    - name: Fetch content of /home/deploy/.ssh/authorized_keys
      ansible.builtin.slurp:
        src: /home/deploy/.ssh/authorized_keys
      register: akeys
    - name: Validate akeys
      ansible.builtin.assert:
        that: >
          "'ssh-rsa ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGH foo@bar.local' in akeys['content'] | b64decode"

    - name: Validate account settings
      ansible.builtin.command: chage -l deploy
      changed_when: false
      register: chage
    - name: Validate akeys
      ansible.builtin.assert:
        that: >
          "'Account expires' in chage.stdout and
          not chage.stdout is match('Account expires.*never') and
          not chage.stdout is match('Last password change.*: password must be changed')"
