---

- name: Verify
  hosts: "{{ playbook_hosts | default('all') }}"
  tasks:
    - name: Fetch content of /home/deploy/.ssh/authorized_keys
      ansible.builtin.slurp:
        src: /home/deploy/.ssh/authorized_keys
      register: akeys
    - name: Validate akeys
      ansible.builtin.assert:
        that:
          - "'ssh-rsa ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGH foo@bar.local' in akeys['content'] | b64decode"

    - name: Validate account settings
      ansible.builtin.command: chage -l deploy
      changed_when: false
      failed_when: false
      register: chage
    - name: Validate akeys
      ansible.builtin.assert:
        that:
          - "'Account expires' in chage.stdout"
          - "not chage.stdout is match('Account expires.*never')"
          - "not chage.stdout is match('Last password change.*: password must be changed')"
      when: ansible_system == "Linux"
    - name: Net+Open BSD | user info
      ansible.builtin.command: userinfo deploy
      changed_when: false
      failed_when: false
      when: ansible_system == "OpenBSD" or ansible_system == "NetBSD"
