---
name: AnsibleCI

on:
  push:
  pull_request:
  schedule:  # run weekly, every monday 01:00
    - cron: '0 1 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - molecule_distro: 'redhat/ubi8'
            experimental: false
          - molecule_distro: 'rockylinux:8'
            experimental: false
          - molecule_distro: 'centos:7'
            experimental: false
          - molecule_distro: 'ubuntu:20.04'
            experimental: false
          - molecule_distro: 'ubuntu:18.04'
            experimental: false
          - molecule_distro: 'ubuntu:16.04'
            experimental: false
          - molecule_distro: 'debian:10'
            experimental: false
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      MOLECULE_NO_LOG: "false"

    steps:
      - uses: actions/checkout@v2
        with:
          path: juju4.adduser
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule[docker] ansible-lint flake8 testinfra ansible
          mkdir -p $HOME/.ansible/roles && ln -s $GITHUB_WORKSPACE/juju4.adduser $HOME/.ansible/roles/
      - name: Environment
        run: |
          pwd
          env
          find -ls
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/juju4.adduser && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
