---
name: Ansible Galaxy release

on:
  release:
    types: [created, edited, published, released]
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: juju4.adduser
  release:
    needs:
      - build
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
